---

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

# does this solve a problem for you? PR's welcome!
#- import_tasks: rhel.yml
#  when: ansible_distribution == 'RedHat'

#- import_tasks: rhel.yml
#  when: ansible_distribution == 'CentOS'

- name: install requirements
  pip: name="cython>=0.20"

- name: set pyzyre version
  set_fact:
    pyzyre_version: master
    pyzyre_debug: 1
  when: pyzyre_version is undefined or pyzyre_version == ""

# production mode- install from pip
- name: install pyzyre
  import_tasks: dist.yml
  when: pyzyre_debug is undefined or pyzyre_debug == False

# in debugmode- install from src
- include_tasks: sdist.yml
  when: pyzyre_debug is defined and pyzyre_debug != ""

- name: test
  command: zyre-broker -h
